Handler
BohdanShchehliuk/Work pull request #4
Opened 2022-08-15 09:30 UTC by BohdanShchehliuk

2022-08-15 09:51 UTC, shurokPetrov requested changes

2022-08-15 09:51 UTC, shurokPetrov commented on Work.iml
>  <?xml version="1.0" encoding="UTF-8"?>
До сих пор этот файл

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/controller/FlightController.java
> +    public static final String ANSI_RED = "\u001B[31m";
Эта переменная нигде не используется

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/controller/FlightController.java
> +        return flightService.getAllFlightsFromStartDataToFinishData(start, finish).toString();
Зачем toString?

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/controller/PassengerController.java
> +    public String savePassenger(@RequestBody PassengerDto passenger) throws UserAlreadyExistException {
Не совсем понятны эти 2 метода
В чем отличии создать пользователя с ДТО и создать пользователя по входных параметрам
Также напоминаю get запрос не безопасен а значит личные данные в нем хранить ни разу не ок

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/controller/PassengerController.java
> +        return Optional.ofNullable(mapToDTO.map(passenger, PassengerDto.class));
Почему ты возвращаешь здесь оptional?

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/controller/PassengerController.java
> +        return list.toString();
toString зачем?

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/dto/FlightDto.java
> +//    {
Комментарии

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/dto/PassengerDto.java
> +//    public Passenger fromDTOToPassenger(PassengerDto requestPassengerDto) {
Комментарии

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/dto/TicketDto.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Точно в DTO должно быть поле с ID аннотацией?

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/entity/Flight.java
> +    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
Рекомендовано никогда не ставить eager

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/entity/Passenger.java
> +    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "passenger", orphanRemoval = true)
Eager

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/exception/Handler.java
> +    public static final String ANSI_RED = "\u001B[31m";
private?

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/exception/Handler.java
> +        log.error(ANSI_RED+ex.getMessage());
Между плюсом все таки лучше сделать пробел

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/exception/UserAlreadyExistException.java
> +@Slf4j
Тут не нужна эта аннотация

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/exception/UserNotFoundException.java
> +@Slf4j
Не нужна эта аннотация

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/exception/UserNotFoundException.java
> +    public Object get() {
Не совсем понимаю логику что ты тут решил описать

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/repository/AircraftRepository.java
> +  }
Скобка
лишний пробел

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/repository/FlightRepository.java
> +    List<Flight> getAllFlightsFromStartDataToFinishData(@Param("startData") LocalDateTime startData, @Param("finishData") LocalDateTime finishData);
Хорошая работа

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/repository/TicketRepository.java
> + @Query("from Ticket t LEFT JOIN FETCH t.flightId f where f.flightNumb =?1")
Текст уехал

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/service/FlightService.java
> +   Optional <Flight> findFlightByFlightNumb(int flight_numb) throws UserNotFoundException;
Текс уехал

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/service/TicketService.java
> +    int TICKET_STATUS_NOT_SOLD = 0;
Я все также рекомендую здесь использовать ENUM 
Ты можешь создать ENUM с двумя полями

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/service/TicketService.java
> +    int TICKET_STATUS_NOT_SOLD = 0;
Но не заморачивайся если нужно будет писать много кода чтоб изменить

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/service/impl/FlightServiceImpl.java
> +        if (!flight1.isEmpty()) throw new UserAlreadyExistException(flight.getId(), "This flight is already existed");
Используй в if всегда { }

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/service/impl/PassengerServiceImpl.java
> +Optional <String> passport = Optional.ofNullable(passenger.getPassport());
Текст уехал

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/service/impl/PassengerServiceImpl.java
> +    @Autowired
Ты можешь повесить AllArgsConstructor и убарть аннотацию

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/service/impl/PassengerServiceImpl.java
> +                .findFirst().isEmpty()) throw new UserNotFoundException("Passenger with such passport dose not exist");
Вот тут скобки нужны как никогда

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/service/impl/TicketServiceImpl.java
> +    @Autowired
Не нужная аннотация у тебя уже стоит AllArgsConstuctor

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/java/airport/service/impl/TicketServiceImpl.java
> +    //       Optional<Flight> flight = Optional.ofNullable(flightRepository.findFlightByFlightNumb(flight_numb));
Комментарий

2022-08-15 09:51 UTC, shurokPetrov commented on src/main/resources/application.properties
> +#debug = true
Комменатрии

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/controller/FlightController.java
> +        return flightService.getAllFlightsFromStartDataToFinishData(start, finish).toString();
Поміняв. Але для цього прийшлось прописати в ентеті fetch = FetchType.EAGER

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/controller/PassengerController.java
> +    public String savePassenger(@RequestBody PassengerDto passenger) throws UserAlreadyExistException {
мтод "/passenger/create/" мені потрібне просто щоб генерувати у правильному форматі passengerDto з яким я можу у подальшому щось робити. Тобто це не основний а допоміжний метод, який я створив виключно для навчальних цілей.

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/controller/PassengerController.java
> +        return Optional.ofNullable(mapToDTO.map(passenger, PassengerDto.class));
Прибрав

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/controller/PassengerController.java
> +        return list.toString();
Тут я на дві години завис. Чомусь не хоче повертати  List<Passenger> list. Поки що залишаю   list.toString();

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/dto/FlightDto.java
> +//    {
видалив

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/dto/PassengerDto.java
> +//    public Passenger fromDTOToPassenger(PassengerDto requestPassengerDto) {
видалив

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/dto/TicketDto.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
)) видалив

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/entity/Flight.java
> +    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
Знаю. Але якщо я лишаю Lazy ... то мені чомусь не повератє у Postaman помилку. Не знаю, це повязано, але чомусь так((  
Тому поки що тут лишаю eager

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/exception/Handler.java
> +        log.error(ANSI_RED+ex.getMessage());
зробив

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/exception/UserAlreadyExistException.java
> +@Slf4j
забрав

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/exception/UserNotFoundException.java
> +@Slf4j
забрав

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/exception/UserNotFoundException.java
> +    public Object get() {
Видалив

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/repository/AircraftRepository.java
> +  }
++

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/repository/FlightRepository.java
> +    List<Flight> getAllFlightsFromStartDataToFinishData(@Param("startData") LocalDateTime startData, @Param("finishData") LocalDateTime finishData);
)))

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/repository/TicketRepository.java
> + @Query("from Ticket t LEFT JOIN FETCH t.flightId f where f.flightNumb =?1")
поправив

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/service/FlightService.java
> +   Optional <Flight> findFlightByFlightNumb(int flight_numb) throws UserNotFoundException;
поправив

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/service/TicketService.java
> +    int TICKET_STATUS_NOT_SOLD = 0;
Зробив enam

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/service/impl/FlightServiceImpl.java
> +        if (!flight1.isEmpty()) throw new UserAlreadyExistException(flight.getId(), "This flight is already existed");
То я вже розлінився))) 
Поміняв

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/service/impl/PassengerServiceImpl.java
> +    @Autowired
Якщо я так роблю, то у Соnfiguration виникають проблеми з бінами
![image](https://user-images.githubusercontent.com/93938769/185159876-a40c0751-9ce0-45d9-90c5-be31373cd62d.png)

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/service/impl/PassengerServiceImpl.java
> +Optional <String> passport = Optional.ofNullable(passenger.getPassport());
поправив

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/service/impl/PassengerServiceImpl.java
> +                .findFirst().isEmpty()) throw new UserNotFoundException("Passenger with such passport dose not exist");
зробив)

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/service/impl/TicketServiceImpl.java
> +    @Autowired
Не працює без @Autowired
![image](https://user-images.githubusercontent.com/93938769/185160231-f62d602f-667d-407a-90f5-fbbcbd0475d4.png)

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/java/airport/service/impl/TicketServiceImpl.java
> +    //       Optional<Flight> flight = Optional.ofNullable(flightRepository.findFlightByFlightNumb(flight_numb));
Забрав

2022-08-17 14:30 UTC, BohdanShchehliuk commented on src/main/resources/application.properties
> +#debug = true
це я собі для прикладу залишив. Якщо дуже хочу розгорнуте логірування - я просто активую коментар

2022-12-15 10:39 UTC, merged